target 'ExampleApp' do

  platform :ios, '9.0'

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native'

  # Pods for node_modules
  pod 'RNImageTools', :path => '../../RNImageTools.podspec'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
